### PR TITLE
Rework the videoPlayer code to restore functionality

### PR DESCRIPTION
**Pull request by zackdotcomputer**
The 1.0.0 distribution was no longer working (would show "video not found"). This PR reworks the webplayer code using the latest sample code from Wistia so it now works again. (It also updates the dependencies to the latest version for cleanliness...)

### CODE REVIEW

**Comment by emomooney** [comment]
Still displaying "Video not found" for me.

**Comment by zackzachariah** [comment]
Would you feel comfortable sharing the video ID you’re testing with? Oh, and the phone model and OS?

**Comment by emomooney** [comment]
Apologies... I didn't realise these changes hadn't been merged yet? I threw your changes in and it does work perfectly. Sorry about that... jumped the gun. Thanks!! 

I am getting warnings about webview being extracted from react-native-core though. Just swapped it out for react-native-webview in the index.js though.

**Review by adhywiranata — APPROVED** [review]

**Comment by adhywiranata** [comment]
Thanks for your PR @zackzachariah ! I haven't got the time to update dependencies considering i'm not using wistia on production at the moment.

**Pull request merged**
